### ISSUE TITLE
Time stamp for phone call issue

### ISSUE THREAD

**Issue by rivei** [stefanotolomeo/Insoles_noAPI#1]
Hi, in the SmartphoneLogReader.java line 77, duration in the phone call log should be in seconds, but the time stamp is in milliseconds. the result of line 78 doesn't seem to give the correct end time of the phone call.

**Comment by stefanotolomeo** [comment]
Hi, 
you are right, just convert seconds in milliseconds in the following way:
long duration = cursor.getInt(2) * 1000;

And it should works fine.
